admin=true
afk=true
autoannouncement=true
back=true
ban=true
broadcast=true
commandspy=true
core=true
customname=true
enderchest=true
extinguish=true
feed=true
fly=true
god=true
hat=true
heal=true
helpop=true
home=true
ignite=true
ignore=true
info=true
inventorysee=true
item=true
jail=true
kick=true
kit=true
mail=true
miscellaneous=true
mute=true
near=true
note=true
notifications=true
placeholders=true
powertool=true
restart=true
rtp=true
seen=true
sign=true
skull=true
smite=true
spawn=true
staffchat=true
styling=true
sudo=true
suicide=true
tablist=true
teleporthere=true
teleportoffline=true
teleportposition=true
teleportrequest=true
tell=true
timebar=true
trash=true
utilities=true
warp=true
