modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[properties]
"connector:placeholder"=true

[[mods]]
modId="solstice"
version="0.0.1"
displayName="Solstice Essentials"
authors="AlexDevs"
description='''Server commands, custom chat formats and more'''

[[dependencies.solstice]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="SERVER"

[[dependencies.solstice]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]"
ordering="NONE"
side="SERVER"

[[dependencies.solstice]]
modId="connector"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"