org.gradle.jvmargs=-Xmx3G

minecraft_version=26.2
loader_version=0.19.3
java_version=25
minecraft_constraint=~26.2

fabric_version=0.154.0+26.2
configurate_version=4.1.2
permissions_api_version=0.7.0
placeholderapi_version=3.1.0-beta.1+26.2
sgui_version=2.1.0+26.2
commoneconomy_version=2.0.0
trinkets_version=4.1.0-beta.2+26.2

vanish_version=1.6.15+26.2
