package me.alexdevs.solstice.modules;

import me.alexdevs.solstice.Solstice;
import me.alexdevs.solstice.api.module.*;
import me.alexdevs.solstice.modules.admin.AdminModule;
import me.alexdevs.solstice.modules.afk.AfkModule;
import me.alexdevs.solstice.modules.announcement.AnnouncementModule;
import me.alexdevs.solstice.modules.back.BackModule;
import me.alexdevs.solstice.modules.ban.BanModule;
import me.alexdevs.solstice.modules.broadcast.BroadcastModule;
import me.alexdevs.solstice.modules.commandSpy.CommandSpyModule;
import me.alexdevs.solstice.modules.cooldown.CooldownModule;
import me.alexdevs.solstice.modules.customName.CustomNameModule;
import me.alexdevs.solstice.modules.enderchest.EnderChestModule;
import me.alexdevs.solstice.modules.experiments.ExperimentsModule;
import me.alexdevs.solstice.modules.extinguish.ExtinguishModule;
import me.alexdevs.solstice.modules.feed.FeedModule;
import me.alexdevs.solstice.modules.fly.FlyModule;
import me.alexdevs.solstice.modules.god.GodModule;
import me.alexdevs.solstice.modules.hat.HatModule;
import me.alexdevs.solstice.modules.heal.HealModule;
import me.alexdevs.solstice.modules.helpOp.HelpOpModule;
import me.alexdevs.solstice.modules.home.HomeModule;
import me.alexdevs.solstice.modules.ignite.IgniteModule;
import me.alexdevs.solstice.modules.ignore.IgnoreModule;
import me.alexdevs.solstice.modules.info.InfoModule;
import me.alexdevs.solstice.modules.inventorySee.InventorySeeModule;
import me.alexdevs.solstice.modules.item.ItemModule;
import me.alexdevs.solstice.modules.jail.JailModule;
import me.alexdevs.solstice.modules.kick.KickModule;
import me.alexdevs.solstice.modules.kit.KitModule;
import me.alexdevs.solstice.modules.mail.MailModule;
import me.alexdevs.solstice.modules.miscellaneous.MiscellaneousModule;
import me.alexdevs.solstice.modules.mute.MuteModule;
import me.alexdevs.solstice.modules.near.NearModule;
import me.alexdevs.solstice.modules.note.NoteModule;
import me.alexdevs.solstice.modules.notifications.NotificationsModule;
import me.alexdevs.solstice.modules.placeholders.PlaceholdersModule;
import me.alexdevs.solstice.modules.powertool.PowerToolModule;
import me.alexdevs.solstice.modules.restart.RestartModule;
import me.alexdevs.solstice.modules.rtp.RTPModule;
import me.alexdevs.solstice.modules.seen.SeenModule;
import me.alexdevs.solstice.modules.sign.SignModule;
import me.alexdevs.solstice.modules.skull.SkullModule;
import me.alexdevs.solstice.modules.smite.SmiteModule;
import me.alexdevs.solstice.modules.spawn.SpawnModule;
import me.alexdevs.solstice.modules.staffChat.StaffChatModule;
import me.alexdevs.solstice.modules.styling.StylingModule;
import me.alexdevs.solstice.modules.sudo.SudoModule;
import me.alexdevs.solstice.modules.suicide.SuicideModule;
import me.alexdevs.solstice.modules.tablist.TabListModule;
import me.alexdevs.solstice.modules.teleportHere.TeleportHereModule;
import me.alexdevs.solstice.modules.teleportOffline.TeleportOfflineModule;
import me.alexdevs.solstice.modules.teleportPosition.TeleportPositionModule;
import me.alexdevs.solstice.modules.teleportRequest.TeleportRequestModule;
import me.alexdevs.solstice.modules.tell.TellModule;
import me.alexdevs.solstice.modules.timeBar.TimeBarModule;
import me.alexdevs.solstice.modules.trash.TrashModule;
import me.alexdevs.solstice.modules.utilities.UtilitiesModule;
import me.alexdevs.solstice.modules.warp.WarpModule;

import java.util.HashSet;

public class ModModuleProvider implements ModuleEntrypoint {
    private static final ModuleRegistry REGISTRY = new ModuleRegistry(Solstice.MOD_ID);

    public static final ModuleContainer<AdminModule> ADMIN = REGISTRY.register("admin", AdminModule::new, new ModuleProperties().toggleable(false));
    public static final ModuleContainer<AfkModule> AFK = REGISTRY.register("afk", AfkModule::new);
    public static final ModuleContainer<AnnouncementModule> ANNOUNCEMENT = REGISTRY.register("autoannouncement", AnnouncementModule::new);
    public static final ModuleContainer<RestartModule> RESTART = REGISTRY.register("restart", RestartModule::new);
    public static final ModuleContainer<BackModule> BACK = REGISTRY.register("back", BackModule::new);
    public static final ModuleContainer<BanModule> BAN = REGISTRY.register("ban", BanModule::new);
    public static final ModuleContainer<BroadcastModule> BROADCAST = REGISTRY.register("broadcast", BroadcastModule::new);
    public static final ModuleContainer<CommandSpyModule> COMMANDSPY = REGISTRY.register("commandspy", CommandSpyModule::new);
    public static final ModuleContainer<CooldownModule> COOLDOWN = REGISTRY.register("cooldown", CooldownModule::new);
    public static final ModuleContainer<CustomNameModule> CUSTOMNAME = REGISTRY.register("customname", CustomNameModule::new);
    public static final ModuleContainer<EnderChestModule> ENDERCHEST = REGISTRY.register("enderchest", EnderChestModule::new);
    public static final ModuleContainer<ExperimentsModule> EXPERIMENTS = REGISTRY.register("experiments", ExperimentsModule::new);
    public static final ModuleContainer<ExtinguishModule> EXTINGUISH = REGISTRY.register("extinguish", ExtinguishModule::new);
    public static final ModuleContainer<FeedModule> FEED = REGISTRY.register("feed", FeedModule::new);
    public static final ModuleContainer<FlyModule> FLY = REGISTRY.register("fly", FlyModule::new);
    public static final ModuleContainer<SignModule> SIGN = REGISTRY.register("sign", SignModule::new);
    public static final ModuleContainer<GodModule> GOD = REGISTRY.register("god", GodModule::new);
    public static final ModuleContainer<HatModule> HAT = REGISTRY.register("hat", HatModule::new);
    public static final ModuleContainer<HealModule> HEAL = REGISTRY.register("heal", HealModule::new);
    public static final ModuleContainer<HelpOpModule> HELPOP = REGISTRY.register("helpop", HelpOpModule::new);
    public static final ModuleContainer<HomeModule> HOME = REGISTRY.register("home", HomeModule::new);
    public static final ModuleContainer<IgniteModule> IGNITE = REGISTRY.register("ignite", IgniteModule::new);
    public static final ModuleContainer<IgnoreModule> IGNORE = REGISTRY.register("ignore", IgnoreModule::new);
    public static final ModuleContainer<InfoModule> INFO = REGISTRY.register("info", InfoModule::new);
    public static final ModuleContainer<InventorySeeModule> INVENTORYSEE = REGISTRY.register("inventorysee", InventorySeeModule::new);
    public static final ModuleContainer<ItemModule> ITEM = REGISTRY.register("item", ItemModule::new);
    public static final ModuleContainer<JailModule> JAIL = REGISTRY.register("jail", JailModule::new);
    public static final ModuleContainer<KickModule> KICK = REGISTRY.register("kick", KickModule::new);
    public static final ModuleContainer<KitModule> KIT = REGISTRY.register("kit", KitModule::new);
    public static final ModuleContainer<MailModule> MAIL = REGISTRY.register("mail", MailModule::new);
    public static final ModuleContainer<MiscellaneousModule> MISCELLANEOUS = REGISTRY.register("miscellaneous", MiscellaneousModule::new);
    public static final ModuleContainer<MuteModule> MUTE = REGISTRY.register("mute", MuteModule::new);
    public static final ModuleContainer<NearModule> NEAR = REGISTRY.register("near", NearModule::new);
    public static final ModuleContainer<NoteModule> NOTE = REGISTRY.register("note", NoteModule::new);
    public static final ModuleContainer<NotificationsModule> NOTIFICATIONS = REGISTRY.register("notifications", NotificationsModule::new);
    public static final ModuleContainer<PlaceholdersModule> PLACEHOLDERS = REGISTRY.register("placeholders", PlaceholdersModule::new);
    public static final ModuleContainer<PowerToolModule> POWERTOOL = REGISTRY.register("powertool", PowerToolModule::new);
    public static final ModuleContainer<RTPModule> RTP = REGISTRY.register("rtp", RTPModule::new);
    public static final ModuleContainer<SeenModule> SEEN = REGISTRY.register("seen", SeenModule::new);
    public static final ModuleContainer<SkullModule> SKULL = REGISTRY.register("skull", SkullModule::new);
    public static final ModuleContainer<SmiteModule> SMITE = REGISTRY.register("smite", SmiteModule::new);
    public static final ModuleContainer<SpawnModule> SPAWN = REGISTRY.register("spawn", SpawnModule::new);
    public static final ModuleContainer<StaffChatModule> STAFFCHAT = REGISTRY.register("staffchat", StaffChatModule::new);
    public static final ModuleContainer<StylingModule> STYLING = REGISTRY.register("styling", StylingModule::new);
    public static final ModuleContainer<SudoModule> SUDO = REGISTRY.register("sudo", SudoModule::new);
    public static final ModuleContainer<SuicideModule> SUICIDE = REGISTRY.register("suicide", SuicideModule::new);
    public static final ModuleContainer<TabListModule> TABLIST = REGISTRY.register("tablist", TabListModule::new);
    public static final ModuleContainer<TeleportHereModule> TELEPORTHERE = REGISTRY.register("teleporthere", TeleportHereModule::new);
    public static final ModuleContainer<TeleportOfflineModule> TELEPORTOFFLINE = REGISTRY.register("teleportoffline", TeleportOfflineModule::new);
    public static final ModuleContainer<TeleportPositionModule> TELEPORTPOSITION = REGISTRY.register("teleportposition", TeleportPositionModule::new);
    public static final ModuleContainer<TeleportRequestModule> TELEPORTREQUEST = REGISTRY.register("teleportrequest", TeleportRequestModule::new);
    public static final ModuleContainer<TellModule> TELL = REGISTRY.register("tell", TellModule::new);
    public static final ModuleContainer<TimeBarModule> TIMEBAR = REGISTRY.register("timebar", TimeBarModule::new);
    public static final ModuleContainer<TrashModule> TRASH = REGISTRY.register("trash", TrashModule::new);
    public static final ModuleContainer<UtilitiesModule> UTILITIES = REGISTRY.register("utilities", UtilitiesModule::new);
    public static final ModuleContainer<WarpModule> WARP = REGISTRY.register("warp", WarpModule::new);

    @Override
    public HashSet<ModuleContainer<?>> register() {
        return REGISTRY.getModules();
    }
}
