package me.alexdevs.solstice.modules;

import me.alexdevs.solstice.Solstice;
import me.alexdevs.solstice.api.module.ModuleBase;
import me.alexdevs.solstice.api.module.ModuleEntrypoint;
import me.alexdevs.solstice.api.module.ModuleRegistry;
import me.alexdevs.solstice.modules.admin.AdminModule;
import me.alexdevs.solstice.modules.afk.AfkModule;
import me.alexdevs.solstice.modules.announcement.AnnouncementModule;
import me.alexdevs.solstice.modules.back.BackModule;
import me.alexdevs.solstice.modules.ban.BanModule;
import me.alexdevs.solstice.modules.broadcast.BroadcastModule;
import me.alexdevs.solstice.modules.commandSpy.CommandSpyModule;
import me.alexdevs.solstice.modules.cooldown.CooldownModule;
import me.alexdevs.solstice.modules.customName.CustomNameModule;
import me.alexdevs.solstice.modules.enderchest.EnderChestModule;
import me.alexdevs.solstice.modules.experiments.ExperimentsModule;
import me.alexdevs.solstice.modules.extinguish.ExtinguishModule;
import me.alexdevs.solstice.modules.feed.FeedModule;
import me.alexdevs.solstice.modules.fly.FlyModule;
import me.alexdevs.solstice.modules.god.GodModule;
import me.alexdevs.solstice.modules.hat.HatModule;
import me.alexdevs.solstice.modules.heal.HealModule;
import me.alexdevs.solstice.modules.helpOp.HelpOpModule;
import me.alexdevs.solstice.modules.home.HomeModule;
import me.alexdevs.solstice.modules.ignite.IgniteModule;
import me.alexdevs.solstice.modules.ignore.IgnoreModule;
import me.alexdevs.solstice.modules.info.InfoModule;
import me.alexdevs.solstice.modules.inventorySee.InventorySeeModule;
import me.alexdevs.solstice.modules.item.ItemModule;
import me.alexdevs.solstice.modules.jail.JailModule;
import me.alexdevs.solstice.modules.kick.KickModule;
import me.alexdevs.solstice.modules.kit.KitModule;
import me.alexdevs.solstice.modules.mail.MailModule;
import me.alexdevs.solstice.modules.miscellaneous.MiscellaneousModule;
import me.alexdevs.solstice.modules.mute.MuteModule;
import me.alexdevs.solstice.modules.near.NearModule;
import me.alexdevs.solstice.modules.note.NoteModule;
import me.alexdevs.solstice.modules.notifications.NotificationsModule;
import me.alexdevs.solstice.modules.placeholders.PlaceholdersModule;
import me.alexdevs.solstice.modules.powertool.PowerToolModule;
import me.alexdevs.solstice.modules.restart.RestartModule;
import me.alexdevs.solstice.modules.rtp.RTPModule;
import me.alexdevs.solstice.modules.seen.SeenModule;
import me.alexdevs.solstice.modules.sign.SignModule;
import me.alexdevs.solstice.modules.skull.SkullModule;
import me.alexdevs.solstice.modules.smite.SmiteModule;
import me.alexdevs.solstice.modules.spawn.SpawnModule;
import me.alexdevs.solstice.modules.staffChat.StaffChatModule;
import me.alexdevs.solstice.modules.styling.StylingModule;
import me.alexdevs.solstice.modules.sudo.SudoModule;
import me.alexdevs.solstice.modules.suicide.SuicideModule;
import me.alexdevs.solstice.modules.tablist.TabListModule;
import me.alexdevs.solstice.modules.teleportHere.TeleportHereModule;
import me.alexdevs.solstice.modules.teleportOffline.TeleportOfflineModule;
import me.alexdevs.solstice.modules.teleportPosition.TeleportPositionModule;
import me.alexdevs.solstice.modules.teleportRequest.TeleportRequestModule;
import me.alexdevs.solstice.modules.tell.TellModule;
import me.alexdevs.solstice.modules.timeBar.TimeBarModule;
import me.alexdevs.solstice.modules.trash.TrashModule;
import me.alexdevs.solstice.modules.utilities.UtilitiesModule;
import me.alexdevs.solstice.modules.warp.WarpModule;

import java.util.HashSet;

public class ModuleProvider implements ModuleEntrypoint {
    private static final ModuleRegistry MODULES = new ModuleRegistry(Solstice.MOD_ID);

    public static final AdminModule ADMIN = MODULES.register(AdminModule::new, "admin");
    public static final AfkModule AFK = MODULES.register(AfkModule::new, "afk");
    public static final AnnouncementModule ANNOUNCEMENT = MODULES.register(AnnouncementModule::new, "autoannouncement");
    public static final RestartModule RESTART = MODULES.register(RestartModule::new, "restart");
    public static final BackModule BACK = MODULES.register(BackModule::new, "back");
    public static final BanModule BAN = MODULES.register(BanModule::new, "ban");
    public static final BroadcastModule BROADCAST = MODULES.register(BroadcastModule::new, "broadcast");
    public static final CommandSpyModule COMMANDSPY = MODULES.register(CommandSpyModule::new, "commandspy");
    public static final CooldownModule COOLDOWN = MODULES.register(CooldownModule::new, "cooldown");
    public static final CustomNameModule CUSTOMNAME = MODULES.register(CustomNameModule::new, "customname");
    public static final EnderChestModule ENDERCHEST = MODULES.register(EnderChestModule::new, "enderchest");
    public static final ExperimentsModule EXPERIMENTS = MODULES.register(ExperimentsModule::new, "experiments");
    public static final ExtinguishModule EXTINGUISH = MODULES.register(ExtinguishModule::new, "extinguish");
    public static final FeedModule FEED = MODULES.register(FeedModule::new, "feed");
    public static final FlyModule FLY = MODULES.register(FlyModule::new, "fly");
    public static final SignModule SIGN = MODULES.register(SignModule::new, "sign");
    public static final GodModule GOD = MODULES.register(GodModule::new, "god");
    public static final HatModule HAT = MODULES.register(HatModule::new, "hat");
    public static final HealModule HEAL = MODULES.register(HealModule::new, "heal");
    public static final HelpOpModule HELPOP = MODULES.register(HelpOpModule::new, "helpop");
    public static final HomeModule HOME = MODULES.register(HomeModule::new, "home");
    public static final IgniteModule IGNITE = MODULES.register(IgniteModule::new, "ignite");
    public static final IgnoreModule IGNORE = MODULES.register(IgnoreModule::new, "ignore");
    public static final InfoModule INFO = MODULES.register(InfoModule::new, "info");
    public static final InventorySeeModule INVENTORYSEE = MODULES.register(InventorySeeModule::new, "inventorysee");
    public static final ItemModule ITEM = MODULES.register(ItemModule::new, "item");
    public static final JailModule JAIL = MODULES.register(JailModule::new, "jail");
    public static final KickModule KICK = MODULES.register(KickModule::new, "kick");
    public static final KitModule KIT = MODULES.register(KitModule::new, "kit");
    public static final MailModule MAIL = MODULES.register(MailModule::new, "mail");
    public static final MiscellaneousModule MISCELLANEOUS = MODULES.register(MiscellaneousModule::new, "miscellaneous");
    public static final MuteModule MUTE = MODULES.register(MuteModule::new, "mute");
    public static final NearModule NEAR = MODULES.register(NearModule::new, "near");
    public static final NoteModule NOTE = MODULES.register(NoteModule::new, "note");
    public static final NotificationsModule NOTIFICATIONS = MODULES.register(NotificationsModule::new, "notifications");
    public static final PlaceholdersModule PLACEHOLDERS = MODULES.register(PlaceholdersModule::new, "placeholders");
    public static final PowerToolModule POWERTOOL = MODULES.register(PowerToolModule::new, "powertool");
    public static final RTPModule RTP = MODULES.register(RTPModule::new, "rtp");
    public static final SeenModule SEEN = MODULES.register(SeenModule::new, "seen");
    public static final SkullModule SKULL = MODULES.register(SkullModule::new, "skull");
    public static final SmiteModule SMITE = MODULES.register(SmiteModule::new, "smite");
    public static final SpawnModule SPAWN = MODULES.register(SpawnModule::new, "spawn");
    public static final StaffChatModule STAFFCHAT = MODULES.register(StaffChatModule::new, "staffchat");
    public static final StylingModule STYLING = MODULES.register(StylingModule::new, "styling");
    public static final SudoModule SUDO = MODULES.register(SudoModule::new, "sudo");
    public static final SuicideModule SUICIDE = MODULES.register(SuicideModule::new, "suicide");
    public static final TabListModule TABLIST = MODULES.register(TabListModule::new, "tablist");
    public static final TeleportHereModule TELEPORTHERE = MODULES.register(TeleportHereModule::new, "teleporthere");
    public static final TeleportOfflineModule TELEPORTOFFLINE = MODULES.register(TeleportOfflineModule::new, "teleportoffline");
    public static final TeleportPositionModule TELEPORTPOSITION = MODULES.register(TeleportPositionModule::new, "teleportposition");
    public static final TeleportRequestModule TELEPORTREQUEST = MODULES.register(TeleportRequestModule::new, "teleportrequest");
    public static final TellModule TELL = MODULES.register(TellModule::new, "tell");
    public static final TimeBarModule TIMEBAR = MODULES.register(TimeBarModule::new, "timebar");
    public static final TrashModule TRASH = MODULES.register(TrashModule::new, "trash");
    public static final UtilitiesModule UTILITIES = MODULES.register(UtilitiesModule::new, "utilities");
    public static final WarpModule WARP = MODULES.register(WarpModule::new, "warp");

    @Override
    public HashSet<ModuleBase> register() {
        return MODULES.getModules();
    }
}
