org.gradle.jvmargs=-Xmx3G

minecraft_version=1.21.1
loader_version=0.16.14
java_version=21
minecraft_constraint=~1.21.1
parchment_mappings=2024.11.17

fabric_version=0.116.4+1.21.1
configurate_version=4.1.2
permissions_api_version=0.3.3
placeholderapi_version=2.4.2+1.21
sgui_version=1.6.1+1.21.1
commoneconomy_version=1.1.1
trinkets_version=3.10.0

