name: Publish (Modrinth, Curseforge, GH, Maven)

on: [ workflow_dispatch ]

env:
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          validate-wrappers: 'true'

      - name: Build
        run: ./gradlew clean build

      - name: Upload built jars
        uses: actions/upload-artifact@v7
        with:
          name: mod-jars
          path: |
            **/build/libs/*.jar
            !**/build/libs/*-sources.jar
            !**/build/libs/*-javadoc.jar
            !**/build/libs/*-plain.jar
          retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ maven, modrinth, curseforge ]
    steps:
      - uses: actions/checkout@v6

      - name: Download built jars
        uses: actions/download-artifact@v8
        with:
          name: mod-jars
          path: .

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: true

      - name: Publish to ${{ matrix.target }}
        run: ./gradlew ${{ matrix.target }} -PprebuiltJar

  github:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download built jars
        uses: actions/download-artifact@v8
        with:
          name: mod-jars
          path: .

      - name: Get Version
        id: get-version
        run: |
          VERSION=$(awk -F'[ ="]+' '$1 == "mod.version" {print $2}' stonecutter.properties.toml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          if [[ "$VERSION" =~ -(alpha|SNAPSHOT) ]]; then
            echo "prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get-version.outputs.version }}
          prerelease: ${{ steps.get-version.outputs.prerelease == 'true' }}
          draft: ${{ steps.get-version.outputs.prerelease == 'true' }}
          generate_release_notes: true
          files: |
            **/build/libs/*.jar
            !**/build/libs/*-sources.jar
            !**/build/libs/*-javadoc.jar
            !**/build/libs/*-plain.jar